name: Deployment
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]       
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install angular
        run: npm link @angular/cli
      - name: Install Packages
        run: npm install
      - name: Build library
        run: ng build resizable-mat-columns
      - name: Build project
        run: npm run build
      - name: Deploy to gh-pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/resizable-columns
          enable_jekyll: true
